### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by Alex-Werner**
### Notables Changelog 

**Breaking Changes:**
- with MemoryAdapter, using getDocument(id) will now return null instead of {_id:id} on unfound document.

**Features:** 
- ObjectID is now exposed by SBTree (#16)
- add isReady method (#18)

**Improvements:**
- removed waitFor deps (#18)

**Fixes:**
- consistency issue with getDocument on unfound doc (#15)
- issue with lower fill factor than order for single element tree (#14)

**Chore, Docs & Tests:**
- chore: updated dependencies to latest (#16) [fslock update brings pretty neat improvement with FSAdapter]

Credits : 
@anuragvohraec for noticing and help bringing the lower fill factor fix

**Notes** : 
- This PR needs documentation update before being able to be merged into master.
- This PR also need addressing #11 before merging.

```
  SBTree - Performance - Standard Benchmark within test 
Will process 5000 elements
Finished writeOp in 110.808466 ms [45122.906042215225] ops
Finished getOp in 41.943944 ms [119206.72028362425] ops
Finished findOp in 792.988534 ms [6305.261407474525] ops
Finished removeOp in 129.437085 ms [38628.805647160545] ops
    ✓ should be fast (1084ms)
======== SBTree 3.0.0 - Benchmark from mocha
= Write : 45122.906042215225 op/s [5000]
= Get : 119206.72028362425 op/s [5000]
= Find : 6305.261407474525 op/s [5000]
= Remove : 38628.805647160545 op/s [5000]
= ======== Summary
= Total : 20000 operations
= Duration : 1.075178029 s
= Avg : 52315.92334511864 op/s
    ✓ should display result

  SBTree - Performance - Extended Benchmark within test 
Will process 5000 elements
Finished writeOp in 57.916768 ms [86330.78420398044] ops
Finished negFindOp in 12127.496229 ms [78.33438840642991] ops
Finished gtFindOp in 9631.042352 ms [202.4702964363] ops
Finished gteFindOp in 10179.926307 ms [186.64182261255735] ops
Finished ltFindOp in 8192.445406 ms [219.7146164296331] ops
Finished lteFindOp in 9654.629499 ms [196.79678025933535] ops
Finished inFindOp in 841.322549 ms [1980.2155570181917] ops
Finished ninFindOp in 22359.199942 ms [59.61751777603027] ops
    ✓ should be fast (73064ms)
======== SBTree 3.0.0 - Extended
= $ne : 78.33438840642991 op/s [950]
= $gt : 202.4702964363 op/s [1950]
= $gte : 186.64182261255735 op/s [1900]
= $lt : 219.7146164296331 op/s [1800]
= $lte : 196.79678025933535 op/s [1900]
= $in : 1980.2155570181917 op/s [1666]
= $nin : 59.61751777603027 op/s [1333]
= ======== Summary
= Total : 16499 operations
= Duration : 73.043979052 s
= Avg : 225.87761803412113 op/s
    ✓ should display result

  SBTree - Performance - Multi-Trees (index/field) benchmark within test 
Will process 10000 elements
Finished writeOp in 435.538025 ms [22960.107788522026] ops
Finished getOp in 88.019057 ms [113611.7602350591] ops
Finished findOp in 1073.957556 ms [9311.354945204184] ops
    ✓ should be fast (1645ms)
======== SBTree 3.0.0 - Multi-tree Benchmark from mocha
= Write : 22960.107788522026 op/s [10000]
= Get : 113611.7602350591 op/s [10000]
= Find : 9311.354945204184 op/s [10000]
= Total : 30000 operations
= Duration : 1.597514638 s
= Avg : 48627.740989595106 op/s
    ✓ should display result
```

### CODE REVIEW

**Comment by anuragvohraec** [comment]
Can you also release it on npm ? Its still 2.3.0 there.

**Comment by Alex-Werner** [comment]
As mentioned in notes, there is still remaining work to do here before being able to merge it. 
Will happen on this week-end :)
As soon as this PR got merged to master, it will be published

**Comment by Alex-Werner** [comment]
Hi @anuragvohraec, 

Do you need me to release 3.0.0 ASAP ? 
I found that there is improvement that I need to do (FsAdapter) that delay any docs update. 
Therefore, if you are in a hurry, I can release 3.0.0 as it is tomorrow, and then came up with an update soon (started but unfinished). 
Or if you have more time (or rely on a `npm install git://github.com/Alex-Werner/SBTree.git#develop`) then it will probably need to wait for next week-end. 

Wishing you an amazing week and staying at your disposal to know what you need the most, in the meantime or in absence of your preference, I will by default go by the second option.

**Comment by anuragvohraec** [comment]
> Or if you have more time (or rely on a `npm install git://github.com/Alex-Werner/SBTree.git#develop`) then it will probably need to wait for next week-end.

Take your time. I will wait.

**Pull request merged**
